(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else if(typeof exports === 'object')
		exports["game-core"] = factory();
	else
		root["game-core"] = factory();
})(window, function() {
return /******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 197);
/******/ })
/************************************************************************/
/******/ ({

/***/ 118:
/***/ (function(module, exports) {

// generated by genversion
module.exports = '1.0.213'


/***/ }),

/***/ 197:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "Launcher", function() { return Launcher; });
/* harmony import */ var _version__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(118);
/* harmony import */ var _version__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(_version__WEBPACK_IMPORTED_MODULE_0__);
// 加载器：
// 1. 在这里接受外部传入的参数并转换为World可以接受的参数
// 2. 做设备兼容
var __awaiter = (undefined && undefined.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (undefined && undefined.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g;
    return g = { next: verb(0), "throw": verb(1), "return": verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (_) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};

var Launcher = /** @class */ (function () {
    function Launcher(config) {
        var _this = this;
        this.minWidth = 1280;
        this.minHeight = 720;
        this.maxWidth = 1920;
        this.maxHeight = 1080;
        this.mConfig = {
            auth_token: Object({"debug":true,"api_root":"http://172.18.0.100:17170/","osd":"https://osd.tooqing.com/","gateway":Object({"host":"172.18.0.103","port":12100,"secure":false}),"game_id":"5e9a7dace87abc390c4b1b73","virtual_world_id":"65541"}).auth_token,
            token_expire: Object({"debug":true,"api_root":"http://172.18.0.100:17170/","osd":"https://osd.tooqing.com/","gateway":Object({"host":"172.18.0.103","port":12100,"secure":false}),"game_id":"5e9a7dace87abc390c4b1b73","virtual_world_id":"65541"}).token_expire,
            token_fingerprint: Object({"debug":true,"api_root":"http://172.18.0.100:17170/","osd":"https://osd.tooqing.com/","gateway":Object({"host":"172.18.0.103","port":12100,"secure":false}),"game_id":"5e9a7dace87abc390c4b1b73","virtual_world_id":"65541"}).token_fingerprint,
            server_addr: undefined,
            game_id: "5e9a7dace87abc390c4b1b73",
            virtual_world_id: "65541",
            // 16:9 = 3840×2160 2560X1440 1920×1080 1600×900 1366×768 1280×720 1024×576 960×540 854×480 720×405
            width: this.minWidth,
            height: this.minHeight,
            screenWidth: this.minWidth,
            screenHeight: this.minHeight,
            baseWidth: this.maxWidth,
            baseHeight: this.maxHeight,
            ui_scale: undefined,
            closeGame: null,
            platform: "pc",
        };
        if (config) {
            Object.assign(this.mConfig, config);
        }
        this.intervalId = setInterval(function () {
            var xhr = new XMLHttpRequest(); // TODO
            xhr.open("GET", "./package.json", true);
            xhr.addEventListener("load", function () {
                var manifest = JSON.parse(xhr.response);
                var newVersion = manifest.version;
                if (_version__WEBPACK_IMPORTED_MODULE_0__["version"] !== newVersion) {
                    var result = confirm("检测到新版本，是否刷新更新到最新版？");
                    if (result && _this.mReload) {
                        _this.mReload();
                    }
                }
            });
            xhr.send(null);
        }, 4 * 60 * 60 * 1000 /* ms */);
        // @ts-ignore
        // import(/* webpackIgnore: true */ "/js/index.js").then((game) => {
        //     this.world = new game.World(this.config, this.mCompleteFunc);
        //     if (config.isEditor) {
        //         this.world.createGame();
        //     }
        //     this.disableClick();
        // });
        this.loadModule("/js/index.js").then(function (game) {
            _this.world = new game.World(_this.config, _this.mCompleteFunc);
        });
    }
    Object.defineProperty(Launcher.prototype, "config", {
        get: function () {
            return this.mConfig;
        },
        enumerable: false,
        configurable: true
    });
    Launcher.start = function (config) {
        return new this(config);
    };
    Launcher.prototype.enableClick = function () {
        if (this.world)
            this.world.enableClick();
    };
    Launcher.prototype.disableClick = function () {
        if (this.world) {
            this.world.disableClick();
        }
        else {
        }
    };
    Launcher.prototype.startFullscreen = function () {
        if (!this.world) {
            return;
        }
        this.world.startFullscreen();
    };
    Launcher.prototype.stopFullscreen = function () {
        if (!this.world) {
            return;
        }
        this.world.stopFullscreen();
    };
    Launcher.prototype.setGameConfig = function (config) {
        if (!this.world)
            return;
        this.world.setGameConfig(config);
    };
    Launcher.prototype.updatePalette = function (palette) {
        if (!this.world)
            return;
        this.world.updatePalette(palette);
    };
    Launcher.prototype.updateMoss = function (moss) {
        if (!this.world)
            return;
        this.world.updateMoss(moss);
    };
    Launcher.prototype.registerReload = function (func) {
        this.mReload = func;
    };
    Launcher.prototype.registerComplete = function (func) {
        this.mCompleteFunc = func;
    };
    Launcher.prototype.onResize = function (width, height, ui_scale) {
        if (!this.world)
            return;
        if (ui_scale)
            this.mConfig.ui_scale = ui_scale;
        this.world.resize(width, height);
        // if (width < height) {
        //     this.world.resize(this.mConfig.screenHeight, this.mConfig.screenWidth);
        // } else {
        //     this.world.resize(this.mConfig.screenWidth, this.mConfig.screenHeight);
        // }
    };
    Launcher.prototype.onOrientationChange = function (orientation, width, height) {
        if (!this.world)
            return;
        this.world.onOrientationChange(orientation, width, height);
    };
    Launcher.prototype.destroy = function () {
        if (this.intervalId)
            clearInterval(this.intervalId);
        if (this.world)
            this.world.destroy();
    };
    Launcher.prototype.loadModule = function (url) {
        return __awaiter(this, void 0, void 0, function () {
            var toExport, esm, esmKeys, exported;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        toExport = {};
                        window.exports = toExport;
                        window.module = { exports: toExport };
                        return [4 /*yield*/, import(/* webpackIgnore: true */ url)];
                    case 1:
                        esm = _a.sent();
                        esmKeys = Object.keys(esm);
                        if (esmKeys.length === 1 && esmKeys[0] === "default")
                            return [2 /*return*/, esm.default];
                        if (esmKeys.length)
                            return [2 /*return*/, esm];
                        exported = window.module.exports;
                        delete window.exports;
                        delete window.module;
                        return [2 /*return*/, exported];
                }
            });
        });
    };
    return Launcher;
}());



/***/ })

/******/ });
});