import { UiManager } from "gamecoreRender";
import { PicaBasePanel } from "../pica.base.panel";
export declare class PicaPlayerInfoPanel extends PicaBasePanel {
    private mBlackBG;
    private background;
    private bgImge;
    private topCon;
    private nickImge;
    private lvImage;
    private vipImage;
    private nickName;
    private content;
    private avatar;
    private middleCon;
    private bottomCon;
    private bottombg;
    private selectLine;
    private mAttrPanel;
    private followBtn;
    private tradingBtn;
    private curToggleItem;
    private mSkillGrideTable;
    private mPlayerData;
    private dataMaps;
    private isOwner;
    private mRelation;
    constructor(uiManager: UiManager);
    resize(width: number, height: number): void;
    hide(): void;
    addListen(): void;
    removeListen(): void;
    init(): void;
    reqPlayerInfo(): void;
    setPlayerData(data: any): void;
    private createOptionButtons;
    private createGrideTable;
    private createNineButton;
    private setFriendRelation;
    private onToggleButtonHandler;
    private onSelectItemHandler;
    private onFollowHandler;
    private onTradingHandler;
    private onPrivateChatHandler;
    private onExitHandler;
    private onMiddleConHandler;
    private onTrackHandler;
    private onIntiveHandler;
    private onGoHomeHandler;
    private onCloseHandler;
    private playMove;
}
