import { FriendRelationEnum } from "structure";
import { BasePanel, UiManager } from "gamecoreRender";
export declare class CharacterInfoPanel extends BasePanel {
    private uiManager;
    private commonkey;
    private bg;
    private labelText;
    private closeBtn;
    private avatar;
    private content;
    private mainCon;
    private lvCon;
    private lvText;
    private nickName;
    private idText;
    private titleName;
    private likeBtn;
    private nickEditor;
    private bottomCon;
    private bottombg;
    private addFriendBtn;
    private tradeBtn;
    private privaCharBtn;
    private mCategoryScroll;
    private mSkillGrideTable;
    private mAttrPanel;
    private editorPanel;
    private curSelectCategeory;
    private isOwner;
    private mBackGround;
    private mExitBtn;
    private mFirendMenu;
    private mCharacterMenu;
    private mCharacterData;
    private mRelation;
    constructor(uiManager: UiManager);
    resize(width: number, height: number): void;
    show(param?: any): void;
    hide(): void;
    update(param: any): void;
    addListen(): void;
    removeListen(): void;
    preload(): void;
    init(): void;
    reqPlayerInfo(): void;
    setPlayerData(data: any): void;
    setFriendRelation(relation: FriendRelationEnum): void;
    destroy(): void;
    private createGrideTable;
    private OnClosePanel;
    private setSubCategory;
    private onSelectSubCategoryHandler;
    private onSelectItemHandler;
    private onEditorHandler;
    private onAddFriendHandler;
    private onTradingHandler;
    private onPrivateChatHandler;
    private onExitHandler;
    private onEditorPanelHideHandler;
    private setMainUIVisible;
    private getRichLabel;
    private getspaceStr;
    private getOptionName;
    private onTrackHandler;
    private onIntiveHandler;
    private onAddBlacklistHandler;
    private onRemoveBlacklistHandler;
}
