import { InputEnable } from "../element/input.enable";
import { IBlockObject } from "./iblock.object";
import { IPos, IFramesModel, IProjection, ISprite } from "structure";
import { MoveControll } from "../../collsion";
import { IRoomService } from "../../room/room";
export declare abstract class BlockObject implements IBlockObject {
    protected mRoomService: IRoomService;
    isUsed: boolean;
    protected mRenderable: boolean;
    protected mBlockable: boolean;
    protected mModel: ISprite;
    protected mInputEnable: InputEnable;
    protected mCreatedDisplay: boolean;
    protected moveControll: MoveControll;
    constructor(id: number, mRoomService: IRoomService);
    setRenderable(isRenderable: boolean, delay?: number): Promise<any>;
    getPosition(): IPos;
    getPosition45(): IPos;
    getRenderable(): boolean;
    fadeIn(callback?: () => void): Promise<any>;
    fadeOut(callback?: () => void): Promise<any>;
    fadeAlpha(alpha: number): void;
    setInputEnable(val: InputEnable): void;
    setBlockable(val: boolean): this;
    destroy(): void;
    moveBasePos(): IPos;
    clear(): void;
    disableBlock(): void;
    enableBlock(): void;
    getProjectionSize(): IProjection;
    load(displayInfo: any): void;
    protected addDisplay(): Promise<any>;
    protected createDisplay(): Promise<any>;
    protected removeDisplay(): Promise<any>;
    protected changeDisplay(displayInfo: IFramesModel): void;
    protected addToBlock(): Promise<any>;
    protected removeFromBlock(remove?: boolean): void;
    protected updateBlock(): void;
    protected addBody(): void;
    protected removeBody(): void;
    protected drawBody(): void;
    protected updateBody(model: any): void;
    private calcBodyPath;
    private prepareVertices;
    private transformBodyPath;
    get id(): number;
    get type(): number;
}
