/// <reference types="phaser" />
import { ItemSlot } from "../../components/item.slot";
import { BasePanel } from "../../components";
import { UiManager } from "../../ui.manager";
export declare class BagPanel extends BasePanel {
    static PageMaxCount: number;
    bagSlotList: ItemSlot[];
    mPreBtn: Phaser.GameObjects.Sprite;
    mNextBtn: Phaser.GameObjects.Sprite;
    private mResStr;
    private mResPng;
    private mResJson;
    private mClsBtn;
    private mPageNum;
    private mPageIndex;
    private mDataList;
    private mBg;
    private mBorder;
    private mInputText;
    private mBaseStr;
    private mCheckList;
    constructor(uiManager: UiManager);
    resize(wid: number, hei: number): void;
    setDataList(items: any): void;
    getPageNum(): number;
    destroy(): void;
    getCurPageIndex(): number;
    show(param?: any): void;
    setBlur(): void;
    addListen(): void;
    removeListen(): void;
    protected init(): void;
    protected preload(): void;
    protected loadComplete(loader: Phaser.Loader.LoaderPlugin, totalComplete: integer, totalFailed: integer): void;
    protected tweenComplete(show: boolean): void;
    private nextHandler;
    private preHandler;
    private preNextBtnScaleHandler;
    private refreshDataList;
    private closeHandler;
    private onFocusHandler;
    private onBlurHandler;
    private checkChinese;
}
