import { UiManager } from "gamecoreRender";
import { op_client } from "pixelpai_proto";
import { PicaBasePanel } from "../pica.base.panel";
export declare class PicaRecastePanel extends PicaBasePanel {
    private mCloseBtn;
    private mBackground;
    private mCategoriesBar;
    private mCategoryCon;
    private mTopBg;
    private mPreCategoryBtn;
    private mSelectedCategeories;
    private mPropGrid;
    private mPropGridBg;
    private mCategoryScroll;
    private confirmBtn;
    private starCountCon;
    private starvalue;
    private displayPanel;
    private starCount;
    private categoryType;
    private mSelectedItemData;
    private mSelectedItem;
    private mRecasteItemData;
    private labelTipTex;
    private tempData;
    constructor(uiManager: UiManager);
    resize(w: number, h: number): void;
    setRecasteResult(data: op_client.CountablePackageItem): void;
    setCategories(subcategorys: any[]): void;
    onShow(): void;
    setProp(props: any[]): void;
    setStarData(value: number): void;
    setRecasteItemData(data: op_client.ICountablePackageItem): void;
    addListen(): void;
    removeListen(): void;
    destroy(): void;
    queryRecasteList(): void;
    protected onInitialized(): void;
    protected init(): void;
    private createNineButton;
    private onSelectSubCategoryHandler;
    private onCloseHandler;
    private onSelectItemHandler;
    private onConfirmBtnHandler;
}
