import { UiManager } from "gamecoreRender";
import { PicaBasePanel } from "../pica.base.panel";
import { op_client } from "pixelpai_proto";
import { IGalleryCombination } from "../../../structure";
export declare class PicaIllustratedPanel extends PicaBasePanel {
    private mBackground;
    private content;
    private listPanel;
    private detailPanel;
    private backButton;
    private titleTex;
    private furiDetail;
    constructor(uiManager: UiManager);
    resize(width?: number, height?: number): void;
    destroy(): void;
    init(): void;
    onShow(): void;
    setGallaryData(content: op_client.OP_CLIENT_REQ_VIRTUAL_WORLD_PKT_UPDATE_GALLERY, combinations: IGalleryCombination[]): void;
    setDoneMissionList(list: number[]): void;
    private openListPanel;
    private showListPanel;
    private hideListPanel;
    private openDetailPanel;
    private showDetailPanel;
    private hideDetailPanel;
    private openFuriDetail;
    private showFuriDetailPanel;
    private hideFuriDetailPanel;
    private onListHandler;
    private onDetailHandler;
    private onFuriDetailHandler;
    private onCloseHandler;
}
