import { Handler } from "utils";
import { IGalleryCombination } from "../../../structure";
export declare class PicaIllustratedDetailPanel extends Phaser.GameObjects.Container {
    private bg;
    private acquire;
    private acquireTex;
    private acquireImg;
    private horProgress;
    private horRewards;
    private curToggle;
    private topCon;
    private toggleCon;
    private selectLine;
    private horLevelTex;
    private levelBg;
    private galleryPanel;
    private collectPanel;
    private dpr;
    private zoom;
    private send;
    private optionType;
    private galleryData;
    private combinations;
    private minit;
    constructor(scene: Phaser.Scene, width: number, height: number, dpr: number, zoom: number);
    resize(width?: number, height?: number): void;
    setHandler(send: Handler): void;
    setGallaryData(content: any, combinations: IGalleryCombination[]): void;
    setHorRewardsStatus(reward1Progress: any, reward1Max: any): void;
    setDoneMissionList(list: number[]): void;
    init(): void;
    protected createOptionButtons(): void;
    private onToggleButtonHandler;
    private layoutOption;
    private onHorRewardsHandler;
    private onAcquireRewardsHandler;
    private onSelectItemHandler;
    private onCollectHandler;
    private onGalleryHandler;
}
