import { Button } from "apowophaserui";
import { UiManager } from "gamecoreRender";
import { PicaBasePanel } from "../pica.base.panel";
import { IExtendCountablePackageItem } from "picaStructure";
export declare class PicaBagPanel extends PicaBasePanel {
    static PICABAG_SHOW: string;
    private mCloseBtn;
    private topCheckBox;
    private mBackground;
    private mCategoriesBar;
    private mCategoryCon;
    private mDetailDisplay;
    private mIconBg;
    private mPreCategoryBtn;
    private mSelectedCategeories;
    private mPropGrid;
    private mPropGridBg;
    private mCategoryScroll;
    private useBtn;
    private showBtn;
    private recasteBtn;
    private topBtns;
    private moneyCon;
    private moneyvalue;
    private diamondvalue;
    private moneyAddBtn;
    private nameText;
    private starImage;
    private moreButton;
    private mDetailBubble;
    private mSceneType;
    private mEnableEdit;
    private isDecorating;
    private categoryType;
    private mSelectedItemData;
    private mSelectedItem;
    private mAttributes;
    private moneyData;
    constructor(uiManager: UiManager);
    get closeBtn(): Button;
    resize(w: number, h: number): void;
    setCategories(subcategorys: any[]): void;
    setProp(props: IExtendCountablePackageItem[], isupdate?: boolean): void;
    setMoneyData(money: number, diamond: number): void;
    setSceneData(sceneType: number, isDecorating: boolean, editor: boolean): void;
    setSelectedResource(content: any): void;
    addListen(): void;
    removeListen(): void;
    destroy(): void;
    queryRefreshPackage(isupdate?: boolean): void;
    onSellPropsHandler(category: number, prop: any, count: number): void;
    onSellPropsFailedHandler(prop: any): void;
    onUsePropsHandler(prop: any, count: number): void;
    onUsePropsFailedHandler(prop: any): void;
    protected onShow(): void;
    protected onInitialized(): void;
    protected init(): void;
    private createCategory;
    private createNineButton;
    private setSelectedItem;
    private isSelectedItemData;
    private onSelectSubCategoryHandler;
    private onCloseHandler;
    private queryPackege;
    private onSelectItemHandler;
    private setItemAttribute;
    private setLayoutAttribute;
    private onAddFurniToSceneHandler;
    private onTopCategoryHandler;
    private clearCategoryData;
    private onSelectedCategory;
    private getPropResource;
    private onMoreButtonHandler;
    private onSellBtnHandler;
    private onUseBtnHandler;
    private onRechargeHandler;
    private onRecasteHandler;
    private onMoreHandler;
    private updateCategeoriesLoc;
    private showPropFun;
    private onShowHandler;
    private get serviceTimestamp();
}
