import { UiManager } from "gamecoreRender";
import { op_client } from "pixelpai_proto";
import { PicaBasePanel } from "../pica.base.panel";
export declare class PicaFurnitureComposePanel extends PicaBasePanel {
    private mCloseBtn;
    private mBackground;
    private topBackground;
    private mCategoriesBar;
    private mCategoryCon;
    private mPreCategoryBtn;
    private mSelectedCategeories;
    private mPropGrid;
    private mPropGridBg;
    private mCategoryScroll;
    private composeBtn;
    private starCountCon;
    private starvalue;
    private furiAnimation;
    private starCount;
    private mSelectedItemData;
    private subCategoryType;
    constructor(uiManager: UiManager);
    resize(w: number, h: number): void;
    setCategories(): void;
    setGridProp(props: any[]): void;
    updateGridProp(props: any[]): void;
    setProps(props: any[]): void;
    setStarData(value: number): void;
    updateSelectItemDatas(props: any[]): void;
    setComposeResult(reward: op_client.ICountablePackageItem): void;
    addListen(): void;
    removeListen(): void;
    destroy(): void;
    queryRefreshPackage(update: any): void;
    protected onInitialized(): void;
    protected init(): void;
    private createNineButton;
    private onSelectSubCategoryHandler;
    private onCloseHandler;
    private queryPackege;
    private onSelectItemHandler;
    private onComposeBtnHandler;
    private checkSelectItemDatas;
    private onFuriComposeAnimationHandler;
}
