import { Handler } from "utils";
export declare class PicaManorShopPanel extends Phaser.GameObjects.Container {
    private bg;
    private titleText;
    private titlebg;
    private closeBtn;
    private dpr;
    private key;
    private closeHandler;
    private sendHandler;
    private imgtitle;
    private secondMenu;
    private corfirmButton;
    private selectedItem;
    private selectedItemData;
    private shopgride;
    private zoom;
    constructor(scene: Phaser.Scene, x: number, y: number, width: number, height: number, key: string, dpr: number, zoom: number);
    refreshMask(): void;
    create(): void;
    setShopCategories(content: any): void;
    setShopDatas(content: any): void;
    setTitleText(text: string): void;
    setHandler(handler: Handler, close: Handler): void;
    private createNineButton;
    private createGrideTable;
    private onTabButtonHandler;
    private onConfirmButtonHandler;
    private onBuyItemHandler;
    private onSelectItemHandler;
    private onCloseHandler;
}
