import { op_client } from "pixelpai_proto";
import { BasePanel, UiManager } from "gamecoreRender";
export declare class TaskPanel extends BasePanel {
    private blackBg;
    private bg;
    private titlebg;
    private tilteName;
    private closeBtn;
    private optionText;
    private optionArrow;
    private optionCon;
    private mGameScroll;
    private taskItems;
    private content;
    private curTaskItem;
    private curOptionItem;
    private taskDatas;
    constructor(uiManager: UiManager);
    resize(width?: number, height?: number): void;
    show(param?: any): void;
    addListen(): void;
    removeListen(): void;
    preload(): void;
    init(): void;
    setTaskDatas(quests: op_client.PKT_Quest[]): void;
    setTaskOptions(): void;
    setTaskDetail(quest: op_client.PKT_Quest): void;
    setTaskItems(quests: op_client.PKT_Quest[]): void;
    destroy(): void;
    private OnClosePanel;
    private onFinishHandler;
    private onExtendsHandler;
    private onOpenOptionHandler;
    private onTaskOptionHandler;
}
