import { UiManager } from "gamecoreRender";
import { PicaBasePanel } from "../pica.base.panel";
import { op_client } from "pixelpai_proto";
export declare class PicaRoamPanel extends PicaBasePanel {
    private mBackground;
    private content;
    private roamListPanel;
    private roamDrawPanel;
    private roamPreviewPanel;
    private roamEffectOnePanel;
    private tokenId;
    private isOneDraw;
    private videoRes;
    constructor(uiManager: UiManager);
    resize(width?: number, height?: number): void;
    preload(): void;
    addListen(): void;
    removeListen(): void;
    destroy(): void;
    init(): void;
    onShow(): void;
    setRoamDataList(pools: []): void;
    openFirstDrawPanel(): void;
    openRoamEffectOnePanel(datas: op_client.ICountablePackageItem[]): void;
    hideRoamEffectOnePanel(): void;
    payDrawHandler(id: string): void;
    setRoamTokenData(money: number, token: number, tokenId: string): void;
    private openRoamList;
    private showRoamListPanel;
    private hideRoamListPanel;
    private openRoamDrawPanel;
    private showRoamDrawPanel;
    private hideRoamDrawPanel;
    private showRoamPreviewPanel;
    private hideRoamPreviewPanel;
    private showRoamEffectOnePanel;
    private onRoamListHandler;
    private onRoamDrawHandler;
    private onRoamPreviewHandler;
    private onRoamEffectOneHandler;
    private onCloseHandler;
}
