import { Handler } from "utils";
import { IDrawPoolStatus } from "src/pica/structure/icardpool";
export declare class PicaRoamDrawPanel extends Phaser.GameObjects.Container {
    private bg;
    private topbg;
    private stripebg;
    private closeBtn;
    private moneyCon;
    private moneyvalue;
    private tokenvalue;
    private moneyAddBtn;
    private drawProgress;
    private oneRoamItem;
    private tenRoamItem;
    private bottomtips;
    private cloudPanel;
    private dpr;
    private zoom;
    private send;
    private money;
    private token;
    private tokenid;
    private poolDatas;
    constructor(scene: Phaser.Scene, width: number, height: number, dpr: number, zoom: number);
    resize(width?: number, height?: number): void;
    setHandler(send: Handler): void;
    init(): void;
    setRoamDatas(datas: IDrawPoolStatus[]): void;
    setMoneyData(money: number, token: number, tokenId: string): void;
    private onRoamDrawHandler;
    private onCloseHandler;
    private onRechargeHandler;
    private onDrawPreviewHandler;
    private onProgressHandler;
}
