import { op_client } from "pixelpai_proto";
import { UiManager } from "gamecoreRender";
import { PicaBasePanel } from "../pica.base.panel";
import { PicaExploreListLevelPanel } from "./PicaExploreListLevelPanel";
export declare class PicaExploreListPanel extends PicaBasePanel {
    static PICAEXPLORELIST_DATA: string;
    levelPanel: PicaExploreListLevelPanel;
    private detialPanel;
    private bottomPanel;
    private bg;
    private topbg;
    private midbg;
    private mBackBtn;
    private energyProgress;
    constructor(uiManager: UiManager);
    resize(width: number, height: number): void;
    addListen(): void;
    removeListen(): void;
    init(): void;
    onShow(): void;
    setExploreChapterResult(content: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_PKT_QUERY_CHAPTER_RESULT): void;
    setExploreChapters(data: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_PKT_EXPLORE_CHAPTER_PROGRESS): void;
    setEnergyData(value: number, max: number): void;
    openDetialPanel(): void;
    hideDetailPanel(): void;
    destroy(): void;
    private onBackHandler;
    private onDetialHandler;
    private onLevelPanelHandler;
    private onBottomPanelHandler;
}
