import { op_client } from "pixelpai_proto";
import { Handler } from "utils";
export declare class PicaExploreListDetailPanel extends Phaser.GameObjects.Container {
    protected dpr: number;
    protected zoom: number;
    private content;
    private bg;
    private blackGraphic;
    private backButton;
    private lineGraphic;
    private titleTex;
    private captoreTex;
    private taskTex;
    private captoreDes;
    private mPropGrid;
    private needItems;
    private labels;
    private needDatas;
    private indexed;
    private labelsCount;
    private send;
    constructor(scene: Phaser.Scene, width: number, height: number, dpr: number, zoom: number);
    resize(w: number, h: number): void;
    setHandler(send: Handler): void;
    setCaptoreResultData(data: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_PKT_QUERY_CHAPTER_RESULT): void;
    protected setNeedItems(datas: op_client.ICountablePackageItem[]): void;
    protected setNeedBottomImgs(count: number): void;
    protected init(): void;
    private setLabelLayout;
    private onHideHandler;
    private createGrid;
    private setLabelsSelect;
    private createGridLayout;
    private onSelectItemHandler;
}
