import { UiManager } from "gamecoreRender";
import { PicaBasePanel } from "../pica.base.panel";
export declare class PicaAvatarPanel extends PicaBasePanel {
    private mCloseBtn;
    private mBackground;
    private mShelfContainer;
    private mDetailDisplay;
    private mBg;
    private mPreCategoryBtn;
    private mSelectedCategeories;
    private mPropGrid;
    private mCategoryScroll;
    private saveBtn;
    private resetBtn;
    private rotateAvatarBtn;
    private nameText;
    private mDetailBubble;
    private mSceneType;
    private categoryType;
    private mSelectedItemData;
    private mSelectedItems;
    private dressAvatarIDS;
    private dressAvatarDatas;
    private isInitAvatar;
    private avatarDirection;
    constructor(uiManager: UiManager, sceneType: any);
    resize(w: number, h: number): void;
    setCategories(subcategorys: any[]): void;
    setProp(props: any[], isupdate?: boolean): void;
    setDressAvatarIds(ids: string[]): void;
    initBaseAvatar(): void;
    displayAvatar(content?: any): void;
    setSelectedResource(content: any): void;
    resetAvatar(avatar: any): void;
    addListen(): void;
    removeListen(): void;
    fetchCategory(): void;
    destroy(): void;
    queryRefreshPackage(isupdate?: boolean): void;
    protected init(): void;
    private createNineButton;
    private setSelectAvatarSuitItem;
    private isSelectedItemData;
    private onSelectSubCategoryHandler;
    private onCloseHandler;
    private queryPackege;
    private onSelectItemHandler;
    private onSelectedCategory;
    private onSaveBtnHandler;
    private onResetBtnHandler;
    private onRotateAvatarHandler;
    private onAvatarClickHandler;
    private getAvatarAni;
    private updateCategeoriesLoc;
    private get serviceTimestamp();
}
