import { Render } from "gamecoreRender";
import { Handler } from "utils";
import { op_client, op_pkt_def } from "pixelpai_proto";
import { PicaTaskItem } from "./PicaTaskItem";
export declare class PicaTaskMainPanel extends Phaser.GameObjects.Container {
    private render;
    taskItems: PicaTaskItem[];
    private gameScroller;
    private curTaskItem;
    private mainItem;
    private mainTaskAnimation;
    private itemTips;
    private notaskTip;
    private dpr;
    private zoom;
    private send;
    private isMoveFinish;
    private questType;
    private isFinishGroup;
    private taskGroupData;
    constructor(scene: Phaser.Scene, width: number, height: number, dpr: number, zoom: number, render: Render);
    setHandler(send: Handler): void;
    refreshMask(): void;
    setTaskDatas(content: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_PKT_QUERY_QUEST_GROUP, questType: op_pkt_def.PKT_Quest_Type): void;
    setTaskDetail(quest: op_client.PKT_Quest): void;
    setTaskItems(quests: op_client.IPKT_Quest[]): void;
    getTaskQuests(quests: op_client.IPKT_Quest[], before: op_client.IPKT_Quest[]): any[];
    playIntoAnimation(): void;
    playGoOutAnimation(): void;
    moveFinish(): void;
    protected init(): void;
    private onPointerUpHandler;
    private onTaskItemHandler;
    private onRewardHandler;
    private onExtendsHandler;
    private onMaterialItemHandler;
}
