import { UiManager } from "gamecoreRender";
import { PicaMyNavigationPanel } from "./PicaMyNavigationPanel";
import { PicaBasePanel } from "../pica.base.panel";
import { op_client } from "pixelpai_proto";
export declare class PicaPartyNavigationPanel extends PicaBasePanel {
    static PicaPartyNavigationPanel_CLOSE: string;
    static PICASELFROOM_DATA: string;
    myRoomPanel: PicaMyNavigationPanel;
    private content;
    private blackBg;
    private bg;
    private tilteName;
    private signProgressPanel;
    private toggleCon;
    private optionLine;
    private selectLine;
    private curToggleItem;
    private itemtips;
    private townPanel;
    private roomPanel;
    private optionType;
    private mPartyData;
    private mNavigationData;
    private progressData;
    private toggleItems;
    constructor(uiManager: UiManager);
    resize(w: number, h: number): void;
    onShow(): void;
    setPartyListData(content: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_PKT_PARTY_LIST, isSelf?: boolean): void;
    setNavigationListData(content: any[]): void;
    setOnlineProgress(content: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_PKT_QUERY_PLAYER_PROGRESS): void;
    setRoomListData(content: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_ROOM_LIST): void;
    setSelfRoomListData(content: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_SELF_ROOM_LIST): void;
    destroy(): void;
    protected onHide(): void;
    protected init(): void;
    protected createOptionButtons(): void;
    private openTownNavigationPanel;
    private hideTownNavigationPanel;
    private openMyRoomPanel;
    private hideMyRoomPanel;
    private openRoomPanel;
    private hideRoomPanel;
    private onToggleButtonHandler;
    private onTownHandler;
    private onProgressHandler;
    private onRoomHandler;
    private onMyRoomHandler;
    private onEnterRoomHandler;
    private showItemTipsState;
    private setTipsPosition;
    private onCloseHandler;
    private playMove;
}
