import { Render } from "gamecoreRender";
export declare class PicaChatInputPanel extends Phaser.Events.EventEmitter {
    private mBackground;
    private bottomCon;
    private contentCon;
    private quickCon;
    private key;
    private sendBtn;
    private cancelBtn;
    private mInput;
    private mOutputText;
    private render;
    private dpr;
    private scene;
    private gamescroll;
    private chatArr;
    private maxChatLength;
    private quickChatScroll;
    private keyboardHeight;
    private quickBg;
    private isOpenQuickPanel;
    private isSendChat;
    private quickChatAtt;
    private isDispose;
    constructor(scene: Phaser.Scene, render: Render, key: string, chatArr: string[]);
    setKeywordHeight(height: number): void;
    setQuickChatData(datas: string[]): void;
    appendChat(val: string): void;
    private onKeyboardHandler;
    private setQuickChatItems;
    private setFirstQuickItem;
    private onBlurHandler;
    private onFocusHandler;
    private onQuickSendHandler;
    private onSentChat;
    private sendChat;
    private onQuickChatItemHandler;
    private onCancelHandler;
}
