import { Button } from "apowophaserui";
import { op_pkt_def, op_def } from "pixelpai_proto";
import { UiManager } from "gamecoreRender";
import { PicaBasePanel } from "../pica.base.panel";
import { PicaNewActivityPanel } from "./PicaNewActivityPanel";
import { PicaNewChatPanel } from "./PicaNewChatPanel";
import { PicaNewHeadPanel } from "./PicaNewHeadPanel";
import { PicaNewLeftPanel } from "./PicaNewLeftPanel";
export declare class PicaNewMainPanel extends PicaBasePanel {
    leftPanel: PicaNewLeftPanel;
    activityPanel: PicaNewActivityPanel;
    protected chatPanel: PicaNewChatPanel;
    protected headPanel: PicaNewHeadPanel;
    protected foldButton: Button;
    private isFold;
    private headData;
    private sceneData;
    constructor(uiManager: UiManager);
    resize(w: number, h: number): void;
    addListen(): void;
    removeListen(): void;
    destroy(): void;
    hide(): void;
    onShow(): void;
    update(param: any): void;
    setPlayerInfo(level: op_pkt_def.IPKT_Level, energy: op_def.IValueBar, money: number, diamond: number): void;
    setRoomInfo(sceneName: string, isPraise: boolean, people: number, roomType: string, isself?: boolean): void;
    setSelfRoomInfo(isself?: boolean): void;
    updateUIState(active?: any): void;
    init(): void;
    fetchFoldButton(fold: boolean): void;
    protected onInitialized(): void;
    private onFoldButtonHandler;
    private onHeadHandler;
    private onLeftHandler;
    private onActivityHandler;
    private onNavigateHandler;
    private checkUpdateActive;
    private onNoticeHandler;
}
