import { Handler } from "utils";
import { op_pkt_def } from "pixelpai_proto";
export declare class PicaNewHeadPanel extends Phaser.GameObjects.Container {
    private dpr;
    private key;
    private headCon;
    private moneyCon;
    private sceneCon;
    private sceneclickCon;
    private levelTex;
    private powerTex;
    private powerPro;
    private powerAddBtn;
    private moneyvalue;
    private diamondvalue;
    private moneyAddBtn;
    private praiseButton;
    private praiseImg;
    private sceneTex;
    private peoplevalue;
    private praisebg;
    private peoplebg;
    private money;
    private diamond;
    private praise;
    private isself;
    private sendHandler;
    private moneyTween;
    constructor(scene: Phaser.Scene, width: number, height: number, key: string, dpr: number);
    init(): void;
    setHeadData(level: op_pkt_def.IPKT_Property, energy: op_pkt_def.IPKT_Property, money: number, diamond: number): void;
    setSceneData(sceneName: string, isPraise: boolean, people: number, roomType: string, isself?: boolean): void;
    setSelfRoomInfo(isself?: boolean): void;
    setHandler(send: Handler): void;
    private onHeadHandler;
    private onEnergyHandler;
    private onPraiseHandler;
    private onRechargeHandler;
    private onOpenHouseHandler;
    private onOpenOnlineHandler;
    private onTooqingHandler;
    private moveMoneyCon;
    private fadeOutHeadCon;
    private canPraise;
    private clearTween;
}
