import { Button } from "apowophaserui";
import { Render } from "gamecoreRender";
import { Handler } from "utils";
export declare class PicaNewActivityPanel extends Phaser.GameObjects.Container {
    private render;
    arrowButton: Button;
    private dpr;
    private key;
    private activityButton;
    private indentButton;
    private rechargeButton;
    private emailButton;
    private roamButton;
    private shopButton;
    private listBtns;
    private listBtns2;
    private listPosY;
    private tempButtons;
    private sendHandler;
    private isFold;
    constructor(render: Render, scene: Phaser.Scene, width: number, height: number, key: string, dpr: number);
    init(): void;
    addListen(): void;
    removeListen(): void;
    setHandler(send: Handler): void;
    updateUIState(datas: any[]): void;
    protected LayoutAllButtons(): void;
    protected LayoutButton(buttons: Button[], posX?: number): any[];
    private onActivityHandler;
    private onIndentHandler;
    private onRechargeHandler;
    private onEmailHandler;
    private onRoamHandler;
    private onShopHandler;
    private onArrowHandler;
    private foldButtons;
    private unfoldButtons;
    private updateAllButtons;
    private updateButtons;
    private getButton;
}
