import { UIManager } from "./ui/ui.manager";
import { PBpacket, PacketHandler } from "net-socket-packet";
import { MainPeer } from "./main.peer";
import { op_def } from "pixelpai_proto";
import { ConnectionService } from "../../lib/net/connection.service";
import { IConnectListener } from "../../lib/net/socket";
import { EventDispatcher } from "utils";
import { GameSocket } from "./net/connection";
import { Clock, ClockReadyListener } from "./loop/clock/clock";
import { HttpClock } from "./loop/httpClock/http.clock";
import { HttpService } from "./loop/httpClock/http.service";
import { LoadingManager } from "./loading/loading.manager";
import { ILauncherConfig } from "structure";
import { IRoomService } from "./room/room/room";
import { ElementStorage } from "../base/model/elementstorage/element.storage";
import { RoomManager } from "./room/room.manager";
import { User } from "./actor/user";
import { DataManager, DataMgrType } from "./data.manager/dataManager";
import { BaseConfigManager } from "./data.manager";
import { NetworkManager } from "./command";
import { SoundManager } from "./sound.manager";
import { GuideManager } from "./guide.manager/guide.manager";
interface ISize {
    width: number;
    height: number;
}
export declare const fps: number;
export declare const interval: number;
export declare class Game extends PacketHandler implements IConnectListener, ClockReadyListener {
    isDestroy: boolean;
    protected mainPeer: MainPeer;
    protected connect: ConnectionService;
    protected mUser: User;
    protected mSize: ISize;
    protected mClock: Clock;
    protected mHttpClock: HttpClock;
    protected mHttpService: HttpService;
    protected mConfig: ILauncherConfig;
    protected mDataManager: DataManager;
    protected mGuideManager: GuideManager;
    protected mRoomManager: RoomManager;
    protected mElementStorage: ElementStorage;
    protected mUIManager: UIManager;
    protected mSoundManager: SoundManager;
    protected mLoadingManager: LoadingManager;
    protected mConfigManager: BaseConfigManager;
    protected mNetWorkManager: NetworkManager;
    protected gameConfigUrls: Map<string, string>;
    protected gameConfigUrl: string;
    protected isPause: boolean;
    protected isAuto: boolean;
    protected mMoveStyle: number;
    protected mReconnect: number;
    protected hasClear: boolean;
    protected currentTime: number;
    protected mWorkerLoop: any;
    protected mAvatarType: op_def.AvatarStyle;
    protected mRunning: boolean;
    constructor(peer: MainPeer);
    addPacketListener(): void;
    removePacketListener(): void;
    get scaleRatio(): number;
    createGame(config?: ILauncherConfig): Promise<void>;
    setConfig(config: ILauncherConfig): void;
    startConnect(): void;
    showLoading(data?: any): void;
    onConnected(isAuto?: boolean): void;
    onDisConnected(isAuto?: boolean): any;
    onRefreshConnect(isAuto?: boolean): void;
    onError(): void;
    reconnect(): Promise<any>;
    exitUser(): void;
    onClientErrorHandler(packet: PBpacket): void;
    destroyClock(): void;
    loadSceneConfig(sceneID: string): Promise<any>;
    clearGameComplete(): void;
    setSize(width: any, height: any): void;
    getSize(): ISize;
    setGameConfig(config: any): void;
    getGameConfig(): ILauncherConfig;
    getDataMgr<T>(type: DataMgrType): T;
    clearClock(): void;
    roomResume(roomID: number): void;
    roomPause(roomID: number): void;
    setCamerasBounds(x: number, y: number, width: number, height: number): void;
    initgameConfigUrls(urls: string[]): void;
    getConfigUrl(sceneId: string): string;
    onClockReady(): void;
    syncClock(times?: number): void;
    set moveStyle(moveStyle: number);
    get moveStyle(): number;
    get httpService(): HttpService;
    get peer(): MainPeer;
    get connection(): ConnectionService;
    get socket(): GameSocket;
    get uiManager(): UIManager;
    get soundManager(): SoundManager;
    get clock(): Clock;
    get httpClock(): HttpClock;
    get elementStorage(): ElementStorage;
    get roomManager(): RoomManager;
    get guideManager(): GuideManager;
    get loadingManager(): LoadingManager;
    get dataManager(): DataManager;
    get configManager(): BaseConfigManager;
    get emitter(): EventDispatcher;
    get user(): User;
    get renderPeer(): any;
    get physicalPeer(): any;
    get avatarType(): op_def.AvatarStyle;
    onFocus(): any;
    onBlur(): void;
    enterVirtualWorld(): Promise<void>;
    login(): void;
    refreshToken(): Promise<void>;
    loginEnterWorld(): Promise<void>;
    leaveRoom(room: IRoomService): void;
    showByName(name: string, data?: any): void;
    showMediator(name: string, isShow: boolean, param?: any): void;
    hideMediator(name: any): void;
    gameCreated(): void;
    /**
     * 加载前端json文件
     * @param name
     */
    loadJson(): void;
    preloadGameConfig(): Promise<any>;
    protected initWorld(): Promise<void>;
    protected createManager(): void;
    private initGame;
    private onGotoAnotherGame;
    private _createAnotherGame;
    private _onGotoAnotherGame;
    private clearGame;
    private onInitVirtualWorldPlayerInit;
    private loadGameConfig;
    private onSelectCharacter;
    private decodeConfigs;
    private onAvatarGameModeHandler;
    private _run;
    private update;
}
export {};
