import { Render } from "gamecoreRender";
import { Handler } from "utils";
export declare class PicaTreasurePreviewPanel extends Phaser.GameObjects.Container {
    protected render: Render;
    private confirmBtn;
    private bg;
    private bgicon;
    private titleimage;
    private titleName;
    private mDetailDisplay;
    private rewardCon;
    private rewardGameScroll;
    private closeBtn;
    private selectMaterial;
    private dpr;
    private zoom;
    private key;
    private treasureData;
    private closeHandler;
    private sendHandler;
    constructor(scene: Phaser.Scene, render: Render, width: number, height: number, key: string, dpr: number, zoom: number);
    resize(w: number, h: number): void;
    addListen(): void;
    removeListen(): void;
    init(): void;
    setHandler(send: Handler, close: Handler): void;
    setTreasureData(datas: any): void;
    private setTreasureItems;
    private onConfirmBtnClick;
    private OnClosePanel;
    private onRewardItemHandler;
}
