import { op_client, op_def } from "pixelpai_proto";
import { PacketHandler, PBpacket } from "net-socket-packet";
import { AStar, ConnectionService, Handler, IPos, IPosition45Obj, LogicPos } from "structure";
import { Game } from "../../game";
import { IScenery, ISprite } from "structure";
import IActor = op_client.IActor;
import { ExtraRoomInfo } from "custom_proto";
import { TerrainManager } from "./terrain/terrain.manager";
import { ElementManager } from "./element/element.manager";
import { PlayerManager } from "./player/player.manager";
import { ICameraService } from "./camera/cameras.worker.manager";
import { EffectManager } from "./effect/effect.manager";
import { SkyBoxManager } from "./sky.box/sky.box.manager";
import { WallManager } from "./element/wall.manager";
import { CollsionManager } from "../collsion";
import { IBlockObject } from "./block/iblock.object";
import { IElement } from "./element/element";
import { ClockReadyListener } from "../loop";
import { IViewBlockManager } from "./viewblock/iviewblock.manager";
import { RoomStateManager } from "./state";
import { IRoomManager } from "./room.manager";
export interface SpriteAddCompletedListener {
    onFullPacketReceived(sprite_t: op_def.NodeType): void;
}
export interface IRoomService {
    readonly id: number;
    readonly terrainManager: TerrainManager;
    readonly elementManager: ElementManager;
    readonly playerManager: PlayerManager;
    readonly cameraService: ICameraService;
    readonly effectManager: EffectManager;
    readonly skyboxManager: SkyBoxManager;
    readonly wallManager: WallManager;
    readonly collsionManager: CollsionManager;
    readonly roomSize: IPosition45Obj;
    readonly miniSize: IPosition45Obj;
    readonly game: Game;
    readonly enableDecorate: boolean;
    readonly sceneType: op_def.SceneTypeEnum;
    readonly isLoading: boolean;
    readonly isDecorating: boolean;
    now(): number;
    enter(room: op_client.IScene): void;
    startPlay(): void;
    pause(): void;
    resume(name: string | string[]): void;
    transformTo45(p: IPos): IPos;
    transformTo90(p: IPos): IPos;
    transformToMini45(p: IPos): IPos;
    transformToMini90(p: IPos): IPos;
    addBlockObject(object: IBlockObject): Promise<any>;
    removeBlockObject(object: IBlockObject): any;
    updateBlockObject(object: IBlockObject): any;
    cameraFollowHandler(): any;
    getElement(id: number): IElement;
    update(time: number, delta: number): void;
    initUI(): void;
    findPath(start: IPos, targetPosList: IPos[], toReverse: boolean): LogicPos[];
    onManagerCreated(key: string): any;
    onManagerReady(key: string): any;
    onRoomReady(): any;
    addToInteractiveMap(sprite: ISprite): any;
    removeFromInteractiveMap(sprite: ISprite): any;
    addToWalkableMap(sprite: ISprite, isTerrain?: boolean): any;
    removeFromWalkableMap(sprite: ISprite, isTerrain?: boolean): any;
    setGroundWalkable(pos: IPos, walkable: boolean): any;
    getInteractiveEles(x: number, y: number): number[][];
    isWalkable(x: number, y: number): boolean;
    checkSpriteConflictToWalkableMap(sprite: ISprite, isTerrain?: boolean, pos?: IPos): number[][];
    destroy(): any;
}
export declare class Room extends PacketHandler implements IRoomService, SpriteAddCompletedListener, ClockReadyListener {
    protected manager: IRoomManager;
    protected mGame: Game;
    protected mID: number;
    protected mTerrainManager: TerrainManager;
    protected mElementManager: ElementManager;
    protected mPlayerManager: PlayerManager;
    protected mSkyboxManager: SkyBoxManager;
    protected mEffectManager: EffectManager;
    protected mSize: IPosition45Obj;
    protected mMiniSize: IPosition45Obj;
    protected mCameraService: ICameraService;
    protected mBlocks: IViewBlockManager;
    protected mEnableDecorate: boolean;
    protected mIsDecorating: boolean;
    protected mWallMamager: WallManager;
    protected mScaleRatio: number;
    protected mStateManager: RoomStateManager;
    protected mAstar: AStar;
    protected mIsLoading: boolean;
    protected mManagersReadyStates: Map<string, boolean>;
    protected mCollsionManager: CollsionManager;
    protected mActorData: IActor;
    protected mUpdateHandlers: Handler[];
    protected mDecorateEntryData: any;
    protected mTerrainMap: number[][];
    protected mWalkableMap: number[][];
    protected mWalkableMarkMap: Map<number, Map<number, {
        level: number;
        walkable: boolean;
    }>>;
    protected mInteractiveList: number[][][];
    protected mIsWaitingForDecorateResponse: boolean;
    constructor(manager: IRoomManager);
    addListen(): void;
    removeListen(): void;
    enter(data: op_client.IScene): void;
    onFullPacketReceived(sprite_t: op_def.NodeType): void;
    onClockReady(): void;
    pause(): void;
    resume(): void;
    addActor(data: IActor): void;
    addBlockObject(object: IBlockObject): Promise<any>;
    removeBlockObject(object: IBlockObject): void;
    updateBlockObject(object: IBlockObject): void;
    transformTo90(p: LogicPos): IPos;
    transformTo45(p: LogicPos): IPos;
    transformToMini90(p: LogicPos): IPos;
    transformToMini45(p: LogicPos): IPos;
    getElement(id: number): IElement;
    update(time: number, delta: number): void;
    updateClock(time: number, delta: number): void;
    now(): number;
    getMaxScene(): {
        width: number;
        height: number;
    };
    createManager(): void;
    startPlay(): Promise<void>;
    initUI(): void;
    addToInteractiveMap(sprite: ISprite): void;
    removeFromInteractiveMap(sprite: ISprite): void;
    addToWalkableMap(sprite: ISprite, isTerrain?: boolean): void;
    removeFromWalkableMap(sprite: ISprite, isTerrain?: boolean): void;
    setGroundWalkable(pos: IPos, walkable: boolean): void;
    getInteractiveEles(x: number, y: number): number[][];
    isWalkable(x: number, y: number): boolean;
    findPath(startPos: IPos, targetPosList: IPos[], toReverse: boolean): LogicPos[];
    clear(): void;
    destroy(): void;
    addUpdateHandler(caller: any, method: Function): void;
    removeUpdateHandler(caller: any, method: Function): void;
    destroyUpdateHandler(): void;
    get isLoading(): boolean;
    onManagerCreated(key: string): void;
    onManagerReady(key: string): void;
    onRoomReady(): void;
    cameraFollowHandler(): void;
    requestSaveDecorating(pkt: PBpacket): void;
    checkSpriteConflictToWalkableMap(sprite: ISprite, isTerrain?: boolean, pos?: IPos): number[][];
    protected initSkyBox(): void;
    protected addSkyBox(scenery: IScenery): void;
    get terrainManager(): TerrainManager;
    get elementManager(): ElementManager;
    get playerManager(): PlayerManager;
    get skyboxManager(): SkyBoxManager;
    get wallManager(): WallManager;
    get cameraService(): ICameraService;
    get effectManager(): EffectManager;
    get collsionManager(): CollsionManager;
    get id(): number;
    get roomSize(): IPosition45Obj | undefined;
    get miniSize(): IPosition45Obj | undefined;
    get blocks(): IViewBlockManager;
    get game(): Game | undefined;
    get enableDecorate(): boolean;
    get isDecorating(): boolean;
    get connection(): ConnectionService | undefined;
    get sceneType(): op_def.SceneTypeEnum;
    protected onEnableEditModeHandler(packet: PBpacket): void;
    protected onShowMapTitle(packet: PBpacket): void;
    protected onCameraResetSizeHandler(): void;
    protected onCameraFollowHandler(packet: PBpacket): void;
    protected onAllSpriteReceived(packet: PBpacket): void;
    protected onReloadScene(packet: PBpacket): void;
    protected onSyncStateHandler(packet: PBpacket): void;
    protected onExtraRoomInfoHandler(content: ExtraRoomInfo): void;
    protected getSpriteWalkableData(sprite: ISprite, isTerrain: boolean, pos?: IPos): {
        origin: IPos;
        collisionArea: number[][];
        walkableArea: number[][];
        pos45: IPos;
        rows: number;
        cols: number;
    };
    protected addWalkableMark(x: number, y: number, id: number, level: number, walkable: boolean): void;
    protected removeWalkableMark(x: number, y: number, id: number): void;
    protected caculateWalkableMark(x: number, y: number): void;
    protected setWalkableMap(x: number, y: number, walkable: boolean): void;
    protected setTerrainMap(x: number, y: number, walkable: boolean): void;
    protected mapPos2Idx(x: number, y: number): number;
    protected setState(state: op_client.IStateGroup): void;
    protected showDecorateGrid(): void;
}
