import { Handler } from "utils";
import { ICountablePackageItem } from "picaStructure";
export declare class ItemsConsumeFunPanel extends Phaser.GameObjects.Container {
    private confirmBtn;
    private dpr;
    private closeBtn;
    private gameScroll;
    private itemtips;
    private title;
    private materialTitle;
    private materialLine;
    private materialLine2;
    private contentTitle;
    private confirmHandler;
    private materialItems;
    private curSelectItem;
    private zoom;
    private havebutton;
    private mblackGraphic;
    private isEnough;
    constructor(scene: Phaser.Scene, width: number, height: number, dpr: number, zoom: number, havebutton?: boolean);
    createBackGrphaic(width: number, height: number): void;
    resetMask(): void;
    setHandler(handler: Handler): void;
    setTextInfo(title: string, materialtitle: string, buttontex?: string): void;
    setItemDatas(datas: ICountablePackageItem[]): void;
    setContent(title: string): void;
    protected create(): void;
    private onConfirmHandler;
    private onCloseHandler;
    private onMaterialItemHandler;
    private setTipsPosition;
}
