import { BasePanel, UiManager } from "gamecoreRender";
export declare class PicaElementStoragePanel extends BasePanel {
    private mBackground;
    private mBorder;
    private mSearchInput;
    private mDragBtn;
    private mProps;
    private mExpaned;
    private mPacgeNum;
    private mPrePageBtn;
    private mNextPageBtn;
    private mItemNum;
    private mDragImage;
    private mDragData;
    private mCloseBtn;
    private mDragging;
    constructor(uiManager: UiManager);
    show(param?: any): void;
    resize(oriention?: number): void;
    addListen(): void;
    removeListen(): void;
    setProps(data: any): void;
    expand(): void;
    collapse(): void;
    destroy(): void;
    protected preload(): void;
    protected init(): void;
    private onPrePageHandler;
    private onNextPageHandler;
    private setPackageNum;
    private switchExpand;
    private onSelectedHandler;
    private onClick;
    private onDragStartHandler;
    private onDragEndHandler;
    private onDragHandler;
    private onPointerOutHandler;
    private clearItem;
    private onCloseHandler;
}
