import { BasicMediator, Game } from "gamecore";
import { PicaRoam } from "./PicaRoam";
import { BaseDataConfigManager } from "../../config";
import { IDrawPoolStatus } from "../../../structure";
export declare class PicaRoamMediator extends BasicMediator {
    protected mModel: PicaRoam;
    protected curMoneyData: any;
    protected poolsData: IDrawPoolStatus[];
    private drawResult;
    constructor(game: Game);
    show(param?: any): void;
    hide(): void;
    panelInit(): void;
    destroy(): void;
    private addLisenter;
    private removeLisenter;
    private onUpdatePlayerInfoHandler;
    private onUpdateHandler;
    private query_ROAM_LIST;
    private query_ROAM_DRAW;
    private query_PROGRESS_REWARD;
    private query_RARE_Effect;
    private onRetRoamListResult;
    private onRetRoamDrawResult;
    private updatePoolsData;
    private updateTokenData;
    private onRetDrawHandler;
    private onRetDrawProgress;
    private onTreasureHideHandler;
    private updateServiceTime;
    get userData(): import("../../../../game").UserDataManager;
    get config(): BaseDataConfigManager;
}
