import { op_client } from "pixelpai_proto";
import { BasePanel, UiManager } from "gamecoreRender";
export declare class PicaComposePanel extends BasePanel {
    private content;
    private mDetailDisplay;
    private mDetailBubble;
    private materialCon;
    private mGrideTable;
    private mSelectItemData;
    private mSelectItem;
    private materialGameScroll;
    private makeBtn;
    private itemtips;
    constructor(uiManager: UiManager);
    resize(width: number, height: number): void;
    show(param?: any): void;
    addListen(): void;
    removeListen(): void;
    preload(): void;
    init(): void;
    destroy(): void;
    setComposeData(datas: op_client.IPKT_CRAFT_SKILL[]): void;
    setComposeDetialData(data: op_client.IPKT_CRAFT_SKILL): void;
    private setDetailDisplay;
    private onSelectItemHandler;
    private setMaterialItems;
    private onMaterialItemHandler;
    private onMakeHandler;
    private onConfirmMakeHandler;
    private onBackHandler;
}
