import { BasePanel, UiManager } from "gamecoreRender";
export declare class PicaMarketPanel extends BasePanel {
    private mSelectItem;
    private mCloseBtn;
    private mTIle;
    private mTabs;
    private mSubTabs;
    private mSelectedCategories;
    private mSelectedSubCategories;
    private mPropContainer;
    private mCategoriesBar;
    private mCategoriesContainer;
    private mSubCategeoriesContainer;
    private mShelfContainer;
    private mBackgroundColor;
    private mShelfBackground;
    private mSubCategorisScroll;
    private mItems;
    private mPreSubCategoris;
    private mPreSubCategorisItem;
    private mPropGrid;
    private randomCon;
    private randomRefeshTime;
    private randomRefreshBtn;
    private refreshIcon;
    private refreshNeedCount;
    private moneycomp;
    private moneyValue;
    private diamondValue;
    constructor(uiManager: UiManager);
    addListen(): void;
    removeListen(): void;
    resize(w: number, h: number): void;
    setCategories(content: any): void;
    setMoneyData(money: number, diamond: number): void;
    setProp(content: any): void;
    setCommodityResource(content: any): void;
    destroy(): void;
    onPropConfirmHandler(prop: any, count: number): void;
    protected layoutCategories(): void;
    protected preload(): void;
    protected init(): void;
    protected setSelect(): void;
    private clearCategories;
    private onSelectCategoryHandler;
    private onSelectSubCategoryHandler;
    private queryProp;
    private onSelectItemHandler;
    private onBuyItemHandler;
    private onCloseHandler;
    private onPopItemCardHandler;
    private getBuyPackageData;
    private showPropFun;
    private getCommodityResource;
}
