import { Handler } from "utils";
export declare class PicaBusinessRankingPanel extends Phaser.GameObjects.Container {
    private titleText;
    private gameScroll;
    private dpr;
    private key;
    private key2;
    private zoom;
    private backHandler;
    private rankHandler;
    private boundOffset;
    private timerID;
    private moveTimerID;
    private mRectangle;
    constructor(scene: Phaser.Scene, x: number, y: number, width: number, height: number, dpr: number, zoom: number, key: string, key2: string);
    create(): void;
    setRankingData(datas: any[]): void;
    setHandler(back: Handler, rank: Handler): void;
    resetMask(): void;
    show(): void;
    hide(): void;
    private onScrollValueChange;
    private onScrollUpHandler;
    private onScrollClickHandler;
    private onBackHandler;
    private addListen;
    private removeListen;
    private pointerDownHandler;
    private pointerUpHandler;
    private checkPointerInBounds;
}
