import { BasePanel, UiManager } from "gamecoreRender";
export declare class PicaBusinessStreetPanel extends BasePanel {
    private key2;
    private content;
    private mBackGround;
    private picMyStreetPanel;
    private picStoreCreatePanel;
    private picSecondStorePanel;
    private picStreetListPanel;
    private picStreetHistoryPanel;
    private picStreetRankingPanel;
    private picRankingDetailPanel;
    private picRankRewardPanel;
    private industryModels;
    constructor(uiManager: UiManager);
    resize(width: number, height: number): void;
    show(param?: any): void;
    addListen(): void;
    removeListen(): void;
    preload(): void;
    init(): void;
    setMyStore(content: any): void;
    setCommercialStreet(content: any): void;
    setIndustryModels(content: any): void;
    setStoreRankingList(content: any): void;
    setStoreRankingDetial(content: any): void;
    setStoreRankingReward(content: any): void;
    setEnterHistory(content: any): void;
    destroy(): void;
    private setSecondStore;
    private openMyStreet;
    private openStoreCreatePanel;
    private openSecondStorePanel;
    private openStoreStreetPanel;
    private openStreetHistoryPanel;
    private openStreetRankingPanel;
    private openRankingDetailPanel;
    private openRankRewardPanel;
    private showMyStreetPanel;
    private hideMyStreetPanel;
    private showStoreCreatePanel;
    private hideStoreCreatePanel;
    private showSecondStorePanel;
    private hideSecondStorePanel;
    private showStreetListPanel;
    private hideStreetListPanel;
    private showStreetHistoryPanel;
    private hideStreetHistoryPanel;
    private showStreetRankingPanel;
    private hideStreetRankingPanel;
    private showRankingDetailPanel;
    private hideRankingDetailPanel;
    private showRankRewardPanel;
    private hideRankRewardPanel;
    private setContentSize;
    private OnCloseHandler;
    private onSelectItemHandler;
    private getRichLabel;
    private getspaceStr;
}
