import { UiManager } from "gamecoreRender";
import { PicaBasePanel } from "../pica.base.panel";
import { op_client } from "pixelpai_proto";
export declare class PicaCreateRolePanel extends PicaBasePanel {
    private commonBackground;
    private mBottomBg;
    private content;
    private sixCon;
    private manButton;
    private womanButton;
    private manIcon;
    private womanIcon;
    private nextButton;
    private suitCon;
    private skinCon;
    private enterButton;
    private backButton;
    private selectSkinBg;
    private dragonbones;
    private consumLeftBtn;
    private consumRightBtn;
    private suitDatasMap;
    private curSuitMap;
    private suitItemMap;
    private mMediator;
    private mgender;
    private consumIndex;
    constructor(uiManager: UiManager);
    resize(wid: number, hei: number): void;
    onShow(): void;
    onResize(gameSize: any): void;
    destroy(): void;
    setSuitDatas(datas: op_client.CountablePackageItem[]): void;
    init(): void;
    protected createSixCon(): void;
    protected createSuitCon(): void;
    private onSubmitHandler;
    private onNextHandler;
    private onAvatarClickHandler;
    private onSixHandler;
    private setSixedSuitsData;
    private setCostumeSuitData;
    private onBackHandler;
    private onSkinHandler;
    private onSuitDataHandler;
    private onConsumLeftHandler;
    private onConsumRightHandler;
    private displayAvatar;
    private loadDragonbonesComplete;
    private creatAvatars;
    get mediator(): any;
}
