var __defProp = Object.defineProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};
export class EventType {
}
__publicField(EventType, "PACKAGE_SYNC_FINISH", "PACKAGE_SYNC_FINISH");
__publicField(EventType, "PACKAGE_UPDATE", "PACKAGE_UPDATE");
__publicField(EventType, "UPDATE_PLAYER_INFO", "UPDATE_PLAYER_INFO");
__publicField(EventType, "UPDATE_ROOM_INFO", "UPDATE_ROOM_INFO");
__publicField(EventType, "UPDATE_EXTRA_ROOM_INFO", "UPDATE_EXTRA_ROOM_INFO");
__publicField(EventType, "UPDATE_PARTY_STATE", "UPDATE_PARTY_STATE");
__publicField(EventType, "SEND_FURNITURE_REQUIREMENTS", "SEND_FURNITURE_REQUIREMENTS");
__publicField(EventType, "SCENE_ELEMENT_DATA_UPDATE", "SCENE_ELEMENT_DATA_UPDATE");
__publicField(EventType, "QUERY_MARKET", "QUERY_MARKET");
__publicField(EventType, "CHAT", "CHAT");
__publicField(EventType, "SCENE_POINT_ELEMENT", "SCENE_ELEMENT");
__publicField(EventType, "SCENE_SHOW_UI", "SCENE_SHOW_UI");
__publicField(EventType, "ELEMENT_ITEM_CONFIG", "ELEMENT_ITEM_CONFIG");
__publicField(EventType, "SEND_GIFT_DATA_UPDATE", "SEND_GIFT_DATA_UPDATE");
__publicField(EventType, "SCENE_ELEMENT_FIND", "SCENE_ELEMENT_FIND");
__publicField(EventType, "SCENE_RETURN_FIND_ELEMENT", "SCENE_RETURN_FIND_ELEMENT");
__publicField(EventType, "SCENE_PLAYER_FIND", "SCENE_PLAYER_FIND");
__publicField(EventType, "SCENE_RETURN_FIND_PLAYER", "SCENE_RETURN_FIND_PLAYER");
__publicField(EventType, "SCENE_INTERACTION_ELEMENT", "SCENE_INTERACTION_ELEMENT");
__publicField(EventType, "SCENE_PLAYER_ACTION", "SCENE_PLAYER_ACTION");
__publicField(EventType, "SCENE_SHOW_MAIN_UI", "SCENE_SHOW_MAIN_UI");
__publicField(EventType, "CHAT_PANEL_EXTPAND", "CHAT_PANEL_EXTPAND");
__publicField(EventType, "SCENE_CHANGE", "SCENE_CHANGE");
__publicField(EventType, "QUERY_SURVEY_FURNITURE", "QUERY_SURVEY_FURNITURE");
__publicField(EventType, "ENTER_SURVEY_FURNITURE_STATUSE", "ENTER_SURVEY_FURNITURE_STATUSE");
__publicField(EventType, "EXECUTE_SURVEY_FURNITURE", "EXECUTE_SURVEY_FURNITURE");
__publicField(EventType, "FECTH_FOLD_MAIN_UI", "FECTH_FOLD_MAIN_UI");
__publicField(EventType, "FETCH_FRIEND", "fetchFriend");
__publicField(EventType, "FOLLOW", "follow");
__publicField(EventType, "UNFOLLOW", "unfollow");
__publicField(EventType, "REMOVE_BAN_USER", "removeBanUser");
__publicField(EventType, "REQ_BLACKLIST", "ReqBlacklist");
__publicField(EventType, "REQ_FRIEND_ATTRIBUTES", "reqFriendAttributes");
__publicField(EventType, "REQ_FRIEND_GAME_DATA", "reqFriendGameData");
__publicField(EventType, "REMOVE_FROM_BLACKLIST", "removeFromBlacklist");
__publicField(EventType, "RENDERER_EVENT", "rendererEvent");
__publicField(EventType, "REQ_PLAYER_LIST", "reqPlayerList");
__publicField(EventType, "PLAYER_LIST", "playerList");
__publicField(EventType, "SEARCH_FRIEND", "searchFriend");
__publicField(EventType, "SEARCH_RESULT", "searchResult");
__publicField(EventType, "REQ_FRIEND_RELATION", "reqFriendRelation");
__publicField(EventType, "REQ_RELATION", "reqRelation");
__publicField(EventType, "REQ_NEW_FANS", "reqNewFans");
__publicField(EventType, "SHOW_MED", "SHOW_MED");
__publicField(EventType, "QUERY_PRAISE", "QUERY_PRAISE");
__publicField(EventType, "QUERY_MARKET_REQUEST", "QUERY_MARKET_REQUEST");
__publicField(EventType, "REQUEST_TARGET_UI", "REQUEST_TARGET_UI");
__publicField(EventType, "NAVIGATE_RESIZE", "navigateResize");
__publicField(EventType, "TEST_COMMAND_MESSAGE", "TEST_COMMAND_MESSAGE");
__publicField(EventType, "GALLERY_UPDATE", "GALLERY_UPDATE");
__publicField(EventType, "DONE_MISSION_LIST", "DONE_MISSION_LIST");
__publicField(EventType, "QUEST_ELEMENT_PI_DATA", "QUEST_ELEMENT_PI_DATA");
__publicField(EventType, "RETURN_ELEMENT_PI_DATA", "RETURN_ELEMENT_PI_DATA");
__publicField(EventType, "RETURN_DRESS_AVATAR_IDS", "RETURN_DRESS_AVATAR_IDS");
__publicField(EventType, "RETURN_UPDATE_RED_SYSTEM", "RETURN_UPDATE_RED_SYSTEM");
__publicField(EventType, "SEND_NEW_PROTO_MESSAGE", "SEND_NEW_PROTO_MESSAGE");
__publicField(EventType, "PACKAGE_TRUMPET_COUNT_UPDATE", "PACKAGE_TRUMPET_COUNT_UPDATE");
__publicField(EventType, "REQUEST_GO_PLAYER_HOME", "REQUEST_GO_PLAYER_HOME");
__publicField(EventType, "REQUEST_GO_ROOM_SCENE", "REQUEST_GO_ROOM_SCENE");
__publicField(EventType, "REQUEST_GO_MINE_READY", "REQUEST_GO_MINE_READY");
