var __defProp = Object.defineProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};
export class MessageType {
}
__publicField(MessageType, "CREATE_ROLE", "create_role");
__publicField(MessageType, "APP_START", "app_start");
__publicField(MessageType, "EDITOR_CHANGE_MODE", "editor_change_mode");
__publicField(MessageType, "CLIENT_RESIZE", "app_client_resize");
__publicField(MessageType, "SCENE_INITIALIZED", "SCENE_INITIALIZED");
__publicField(MessageType, "SCENE_CLEARED", "SCENE_CLEARED");
__publicField(MessageType, "SCENE_CHANGE_TO", "SCENE_CHANGE_TO");
__publicField(MessageType, "SCENE_MOVE_TO", "scene_move_to");
__publicField(MessageType, "SCENE_MOVE_STOP", "scene_move_stop");
__publicField(MessageType, "CHANGE_ELEMENT_ANIMATION", "change_element_animation");
__publicField(MessageType, "CHANGE_CHARACTER_ANIMATION", "change_character_animation");
__publicField(MessageType, "CHAT_TO", "chat_to");
__publicField(MessageType, "SHOW_CHAT_BUBBLE", "show_chat_bubble");
__publicField(MessageType, "REMOVE_CHAT_BUBBLE", "remove_chat_bubble");
__publicField(MessageType, "PROMPT_ALERT", "prompt_alert");
__publicField(MessageType, "CHARACTER_TALING", "characterTaling");
__publicField(MessageType, "CHARACTER_SHUT_UP", "characterShutUp");
__publicField(MessageType, "QCLOUD_AUTH", "qcloud_auth");
__publicField(MessageType, "ENTER_SCENE", "enter_scene");
__publicField(MessageType, "SCENE_ADD_PLAYER", "scene_add_player");
__publicField(MessageType, "SCENE_REMOVE_PLAYER", "scene_remove_player");
__publicField(MessageType, "SCENE_UPDATE_PLAYER", "scene_update_player");
__publicField(MessageType, "SCENE_ADD_ELEMENT", "scene_add_element");
__publicField(MessageType, "SCENE_ADD_TERRAIN", "scene_add_terrain");
__publicField(MessageType, "SCENE_ADD_TERRAIN_END", "scene_add_terrain_end");
__publicField(MessageType, "SCENE_ADD_ALL_TERRAIN", "scene_add_all_terrain");
__publicField(MessageType, "SCENE_REMOVE_ELEMENT", "scene_remove_element");
__publicField(MessageType, "SCENE_REMOVE_TERRAIN", "scene_remove_terrain");
__publicField(MessageType, "SCENE_REMOVE_ALL_TERRAIN", "scene_remove_all_terrain");
__publicField(MessageType, "SCENE_MOUSE_FOLLOW", "scene_mouse_follow");
__publicField(MessageType, "SCENE_SELECT_ELEMENT", "scene_select_element");
__publicField(MessageType, "SCENE_FIXED_TO_ELEMENT", "scene_fixed_to_element");
__publicField(MessageType, "SCENE_UPDATE_ELEMENT", "sceneUpdateElement");
__publicField(MessageType, "SCENE_SYNCHRO_PACKAGE", "sceneSynchroPackage");
__publicField(MessageType, "SCENE_VISIBLE_GRID", "sceneVisibleGrid");
__publicField(MessageType, "PLAYER_SELECT_CHARACTER", "player_select_character");
__publicField(MessageType, "PLAYER_DATA_INITIALIZE", "player_data_initialize");
__publicField(MessageType, "SCENE_DATA_INITIALIZE", "scene_data_initialize");
__publicField(MessageType, "PACKAGE_ITEM_ADD", "package_item_add");
__publicField(MessageType, "PACKAGE_ITEM_REMOVE", "package_item_remove");
__publicField(MessageType, "PACKAGE_EXCHANGE_ITEM_POS", "package_exchange_item_pos");
__publicField(MessageType, "SCENE_BACKGROUND_CLICK", "SCENE_BACKGROUND_CLICK");
__publicField(MessageType, "CHANGE_SELF_AVATAR", "CHANGE_SELF_AVATAR");
__publicField(MessageType, "DRAG_TO_DROP", "DRAG_TO_DROP");
__publicField(MessageType, "DRAG_OVER_DROP", "DRAG_OVER_DROP");
__publicField(MessageType, "QUERY_PACKAGE", "query_package");
__publicField(MessageType, "SYNC_USER_BALANCE", "syncUserBalance");
__publicField(MessageType, "UPDATED_CHARACTER_PACKAGE", "updatedCharacterPackage");
__publicField(MessageType, "SHOW_EFFECT", "showEffect");
__publicField(MessageType, "EDIT_MODE_QUERY_PACKAGE", "editModeQueryPackage");
__publicField(MessageType, "PRESS_ELEMENT", "PRESS_ELEMENT");
__publicField(MessageType, "TURN_ELEMENT", "turnElement");
__publicField(MessageType, "RECYCLE_ELEMENT", "recycleElement");
__publicField(MessageType, "PUT_ELEMENT", "putElement");
__publicField(MessageType, "CANCEL_PUT", "cancelPut");
__publicField(MessageType, "EDIT_PACKAGE_EXPANED", "editPackageExpaned");
__publicField(MessageType, "EDIT_PACKAGE_COLLAPSE", "editPackageCollapse");
__publicField(MessageType, "DECORATE_SELECTE_ELEMENT", "decorateSelecteElement");
__publicField(MessageType, "DECORATE_UNSELECT_ELEMENT", "decorateUnselectElement");
__publicField(MessageType, "DECORATE_UPDATE_SELECTED_ELEMENT_CAN_PLACE", "decorateUpdateSelectedElementCanPlace");
__publicField(MessageType, "DECORATE_UPDATE_SELECTED_ELEMENT_POSITION", "decorateUpdateSelectedElementPosition");
__publicField(MessageType, "DECORATE_UPDATE_ELEMENT_COUNT", "decorateUpdateElementCount");
__publicField(MessageType, "DECORATE_ELEMENT_CREATED", "decorateElementCreated");
__publicField(MessageType, "ADD_ICON_TO_TOP", "addIconToTop");
__publicField(MessageType, "REMOVE_ICON_FROM_TOP", "removeIconFromTop");
__publicField(MessageType, "SHOW_UI", "showUI");
__publicField(MessageType, "SHOW_NOTICE", "showNotice");
