import { AvatarSuit } from "structure";
import { UiManager } from "gamecoreRender";
import { PicaBasePanel } from "../pica.base.panel";
export declare class PicaRenamePanel extends PicaBasePanel {
    private commonBackground;
    private mBottomBg;
    private content;
    private backButton;
    private dragonbones;
    private inputCon;
    private enterButton;
    private randomButton;
    private inputTex;
    constructor(uiManager: UiManager);
    resize(wid: number, hei: number): void;
    setSuitDatas(datas: AvatarSuit[]): void;
    init(): void;
    setNickName(val: string): void;
    addListen(): void;
    removeListen(): void;
    private onTextBlurHandler;
    private onTextFocusHandler;
    private onGameobjectDown;
    private onSubmitHandler;
    private onRandomNameHandler;
    private onAvatarClickHandler;
    private onBackHandler;
    private displayAvatar;
    private loadDragonbonesComplete;
}
