import { BasePanel, UiManager } from "gamecoreRender";
export declare class PicaLoginPanel extends BasePanel {
    private readonly areaCode;
    private mPhoneInput;
    private mPhoneCodeInput;
    private fetchTime;
    private acceptBtn;
    private downcount;
    private fetchCode;
    private mMediator;
    private mLoginBtn;
    private mErrorTips;
    private mMaskBg;
    private parent;
    private mCloseBtn;
    private errorCode;
    constructor(uiManager: UiManager);
    setInputVisible(val: boolean): void;
    destroy(): void;
    setLoginEnable(val: any): void;
    addListen(): void;
    removeListen(): void;
    showError(response: any): void;
    resize(): void;
    protected preload(): void;
    protected init(): void;
    private updatePanelList;
    private createInput;
    private onFetchCodeHandler;
    private tryLogin;
    private onEnterPhoneHandler;
    private onEnterCodeHandler;
    private onCheckboxHandler;
    private onLoginHandler;
    private onCodeChangeHandler;
    private onCloseHandler;
}
