import { BasePanel, UiManager } from "gamecoreRender";
export declare class PicaNavigatePanel extends BasePanel {
    private readonly key_lang;
    private mBackground;
    private mMapBtn;
    private mShopBtn;
    private mBagBtn;
    private mFamilyBtn;
    private mGoHomeBtn;
    private mCloseBtn;
    constructor(uiManager: UiManager);
    resize(w: number, h: number): void;
    addListen(): void;
    removeListen(): void;
    hide(): void;
    show(param?: any): void;
    updateUIState(active?: any): void;
    get isZh_CN(): boolean;
    protected preload(): void;
    protected init(): void;
    private createButton;
    private createImage;
    private createSprite;
    private onShowMapHandler;
    private onShowShopHandler;
    private onShowBagHandler;
    private onShowFamilyHandler;
    private onShowGoHomeHandler;
    private onCloseHandler;
    private checkUpdateActive;
}
