import { op_client, op_gameconfig, op_gameconfig_01, op_def } from "pixelpai_proto";
import { LogicPoint } from "./logic.point";
import { AnimationQueue, RunningAnimation } from "./animation";
import { Animator } from "./animator";
import { AvatarSuit } from "./avatar.suit.type";
import { IAvatar, IDragonbonesModel } from "./dragonbones";
import { IFramesModel } from "./frame";
import { IPos } from "./logic.pos";
export interface ISprite {
    id: number;
    avatar: IAvatar;
    titleMask: number;
    nickname: string;
    alpha: number;
    displayBadgeCards: op_def.IBadgeCard[];
    sound: string;
    platformId: string;
    sceneId: number;
    nodeType: op_def.NodeType;
    currentAnimation: RunningAnimation;
    currentCollisionArea: number[][];
    currentWalkableArea: number[][];
    currentCollisionPoint: LogicPoint;
    hasInteractive: boolean;
    interactive: op_def.IPBPoint2f[];
    attrs: op_def.IStrPair[];
    suits: AvatarSuit[];
    animationQueue: AnimationQueue;
    currentAnimationName: string;
    displayInfo: IFramesModel | IDragonbonesModel;
    direction: number;
    pos: IPos;
    bindID: number;
    sn: string;
    isMoss?: boolean;
    mountSprites?: number[];
    speed: number;
    animator?: Animator;
    updateSuits?: boolean;
    layer?: number;
    newID(): any;
    updateAvatar(avatar: IAvatar): any;
    setTempAvatar(avatar: IAvatar): any;
    updateDisplay(display: op_gameconfig.IDisplay, animations: op_gameconfig_01.IAnimationData[], defAnimation?: string): any;
    setPosition(x: number, y: number): any;
    setAnimationName(name: string, playTimes?: number): RunningAnimation;
    setAnimationQueue(queue: AnimationQueue): any;
    setDirection(val: any): any;
    setDisplayInfo(val: any): any;
    updateAttr(attrs: op_def.IStrPair[]): any;
    updateAvatarSuits(suits: AvatarSuit[]): boolean;
    getCollisionArea(): number[][];
    getWalkableArea(): number[][];
    getOriginPoint(): IPos;
    getInteractive(): any;
    turn(): ISprite;
    toSprite(): op_client.ISprite;
    registerAnimationMap(key: string, value: string): any;
    unregisterAnimationMap(key: string): any;
}
