import { op_client } from "pixelpai_proto";
import { Handler } from "utils";
import { ButtonEventDispatcher } from "gamecoreRender";
export declare class PicaExploreLogSettlePanel extends ButtonEventDispatcher {
    protected dpr: number;
    protected zoom: number;
    private blackGraphic;
    private titleimage;
    private starPro;
    private starText;
    private scorebg;
    private scoreTex;
    private content;
    private lightImg;
    private scoreTipsCon;
    private curLayoutGroup;
    private maskGraphic;
    private unkownImg;
    private settleData;
    private scoreDatas;
    private closeHandler;
    private tweens;
    private curFadeOutObj;
    private curFadeInObj;
    private maskWidth;
    private maskHeight;
    private scoreTimer;
    private curTempScore;
    private allScore;
    private isPlayed;
    private finished;
    private received;
    constructor(scene: Phaser.Scene, width: number, height: number, dpr: number, zoom: number);
    resize(w: number, h: number): void;
    init(): void;
    setHandler(close: Handler): void;
    destroy(): void;
    setSettleData(content: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_PKT_EXPLORE_SUMMARY): void;
    private initParam;
    private getScoreArr;
    private setLayoutMask;
    private excuteNextDatas;
    private playScoreTipsAnimation;
    private clearScoreAnimation;
    private playCalculateScoreAnimation;
    private playScoreTipsFadeIn;
    private playScoreTipsFadeOut;
    private playStarAnimation;
    private getProgressValue;
    private setStarProgressInfo;
    private playLayoutAnimation;
    private playItemTween;
    private playLightAnimation;
    private playtPosYTween;
    private playAlphaTween;
    private removeTween;
    private createLayoutGroup;
    private onClickHandler;
}
