import { op_client } from "pixelpai_proto";
import { UiManager } from "gamecoreRender";
import { PicaBasePanel } from "../pica.base.panel";
export declare class PicaExploreLogPanel extends PicaBasePanel {
    private goOutBtn;
    private continueProgress;
    private continueText;
    private expProgress;
    private textCon;
    private settlePanel;
    private rotateTween;
    private guideCon;
    private timer;
    constructor(uiManager: UiManager);
    resize(width: number, height: number): void;
    addListen(): void;
    removeListen(): void;
    init(): void;
    setExploreDatas(texts: string[]): void;
    setExploreCountDown(content: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_PKT_EXPLORE_SHOW_COUNTDOWN): void;
    setExploreSettleDatas(content: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_PKT_EXPLORE_SUMMARY): void;
    setExploreGuideTexts(content: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_PKT_ROOM_SHOW_GUIDE_TEXT): void;
    setTimeProgress(time: any): void;
    openSettlePanel(): void;
    hideSettlePanel(): void;
    setTipsLayout(extpand: boolean): void;
    destroy(): void;
    private onProClickHandler;
    private onGoOutHandler;
    private onSettleHandler;
    private clearTimer;
    private playRotateTween;
    private clearRotateTween;
    private continueFadeOutAnimation;
}
