import { ResourcesChangeListener } from "./element.editor.resource.manager";
import ElementEditorGrids from "./element.editor.grids";
import { BaseFramesDisplay } from "baseRender";
import { AnimationDataNode } from "game-capsule";
export declare const LOCAL_HOME_PATH: string;
export declare class ElementFramesDisplay extends BaseFramesDisplay implements ResourcesChangeListener {
    private mWebHomePath;
    private readonly MOUNT_ANIMATION_TIME_SCALE;
    private mGrids;
    private mEmitter;
    private mSelectedGameObjects;
    private mAnimationData;
    private mCurFrameIdx;
    private mPlaying;
    private mCurMountAnimation;
    constructor(scene: Phaser.Scene, node: any, grids: ElementEditorGrids, emitter: Phaser.Events.EventEmitter, mWebHomePath: string);
    setAnimationData(data: AnimationDataNode): void;
    onResourcesLoaded(): void;
    onResourcesCleared(): void;
    setFrame(frameIdx: number): void;
    setMountAnimation(aniName: string, idx?: number): void;
    updateMountDisplay(): void;
    setPlay(playing: boolean): void;
    setInputEnabled(val: boolean): void;
    setSelectedAnimationLayer(idxs: number[]): void;
    setSelectedMountLayer(mountPointIndex?: number): void;
    updateDepth(): void;
    updatePerAnimationLayerVisible(idx: number): void;
    addAnimationLayer(idx: number): void;
    updateAnimationLayer(): void;
    updateOffsetLoc(idx: number): void;
    generateThumbnail(): Promise<string>;
    clear(): void;
    protected clearDisplay(): void;
    protected makeAnimation(gen: string, key: string, frameName: string[], frameVisible: boolean[], frameRate: number, loop: boolean, frameDuration?: number[]): void;
    protected createDisplays(key?: string, ani?: any): void;
    private dragonBoneLoaded;
    private keyboardEvent;
    private onDragStartHandler;
    private onDragHandler;
    private onDragEndHandler;
    private syncPositionData;
    private updatePlay;
    private updateMountLayerPlay;
    private onMountTimerEvent;
    private setSelectedGameObjects;
    private getMaskValue;
    private updateInputEnabled;
    private updatePerInputEnabled;
    private updateChildrenIdxByDepth;
}
