import { op_client } from "pixelpai_proto";
import { UiManager } from "gamecoreRender";
export declare class PicaOpenPartyCreatePanel extends Phaser.GameObjects.Container {
    private uiManager;
    private key;
    private dpr;
    private partyNameTitle;
    private mNameInput;
    private partyThemeTitle;
    private gamegride;
    private describleTitle;
    private describleInput;
    private partyTimeTitle;
    private timeSlider;
    private thumb;
    private itemCountText;
    private itemCount;
    private partyTimeLable;
    private partyTimevalue;
    private partyCardImage;
    private overageTitle;
    private overageValue;
    private openBtn;
    private curPartyData;
    private curSelectItem;
    private expiredTime;
    private timer;
    private partyData;
    private zoom;
    private render;
    constructor(uiManager: UiManager, x: number, y: number, width: number, height: number, key: string, dpr: number, zoom: number);
    resize(): void;
    hide(): void;
    show(): void;
    destroy(fromScene?: boolean): void;
    setPartyData(content: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_PKT_CREATE_PARTY_REQUIREMENTS, username: string, servertime: number): void;
    private setExpiredValue;
    private setPartyInfoType;
    private changeInputState;
    private create;
    private createSlider;
    private onSliderValueHandler;
    private onTextChangeHandler;
    private onOpenPartyHandler;
    private onGridTableHandler;
    private createInput;
}
