import { op_client, op_pkt_def } from "pixelpai_proto";
import { BasePanel, UiManager } from "gamecoreRender";
export declare class PicaMainUIPanel extends BasePanel {
    private mCoinValue;
    private mDiamondValue;
    private mSceneName;
    private mCounter;
    private mStrengthValue;
    private playerLv;
    private playerIcon;
    private playerCon;
    private roomCon;
    private textToolTip;
    private isSceneNameActive;
    private praiseBtn;
    private praiseImg;
    private partyBtn;
    private playerInfo;
    private roomInfo;
    private headImage;
    constructor(uiManager: UiManager);
    show(param?: any): void;
    resize(w: number, h: number): void;
    preload(): void;
    addListen(): void;
    removeListen(): void;
    destroy(): void;
    update(param: any): void;
    updatePlayerInfo(player: op_client.IOP_VIRTUAL_WORLD_REQ_CLIENT_PKT_PLAYER_INFO): void;
    updateDetail(detail: any): void;
    getCoin(): op_pkt_def.IPKT_Property;
    getDiamond(): op_pkt_def.IPKT_Property;
    updateRoomInfo(room: any): void;
    get isSelfRoom(): boolean;
    updateUIState(active?: any): void;
    init(): void;
    private onOpenRoomPanel;
    private onHeadHandler;
    private onStrengthHandler;
    private onTextToolTipHandler;
    private checkUpdateActive;
    private onUpdatePlayerHandler;
    private onUpdateRoomHandler;
    private onUpdatePartyHandler;
    private onPraiseHandler;
    private onPartyHandler;
    private onOpenRechargeHandler;
}
