import { BasePanel, UiManager } from "gamecoreRender";
export declare class PicaRechargePanel extends BasePanel {
    private mBackground;
    private bg;
    private topbg;
    private titlebg;
    private tilteName;
    private closeBtn;
    private diamondvalue;
    private gridlayout;
    private content;
    private middle;
    private top;
    private gamescroll;
    private bottombg;
    private bottom;
    private checkBox;
    private itemtips;
    private banner;
    constructor(uiManager: UiManager);
    resize(width?: number, height?: number): void;
    show(param?: any): void;
    addListen(): void;
    removeListen(): void;
    preload(): void;
    init(): void;
    setDataList(): void;
    destroy(): void;
    protected createMiddle(width: number, height: number): void;
    protected createBottom(width: number, height: number): void;
    private createGameScroll;
    private buy;
    private onTabButtonHandler;
    private OnClosePanel;
    private onPointerUpHandler;
    private onSendHandler;
    private onItemInfoTips;
    private getDesText;
}
