import { op_client } from "pixelpai_proto";
export declare class PicaEquipUpgradeItem extends Phaser.Events.EventEmitter {
    private bg;
    private topbg;
    private bottombg;
    private unlockbtn;
    private unlockBg;
    private titleName;
    private equipName;
    private penetrationText;
    private gridTable;
    private equipDes;
    private dpr;
    private key;
    private commonKey;
    private diamondIcon;
    private costNum;
    private btnName;
    private unlockCondition;
    private haveEquiped;
    private curEquipItem;
    private curSelectItemData;
    private zoom;
    private cellWidth;
    private cellHeight;
    private mScene;
    private mContainer;
    constructor(scene: Phaser.Scene, container: Phaser.GameObjects.Container, dpr: number, zoom: number, key: string, commonKey: string);
    setEquipItems(data: op_client.IMiningEquipmenetArray): void;
    setTransPosition(x: number, y: number): void;
    get displayList(): any[];
    refreshEquipData(data: op_client.IMiningEquipment, index: number): void;
    destroy(): void;
    private setBgTexture;
    private create;
    private createGridTable;
    private onSelectItemHandler;
    private updateEquipItem;
    private onUnlockEquipHandler;
    private createBtn;
}
