/// <reference types="tooqingphaser" />
import { IListItemComponent } from "../bag/IListItemRender";
import { op_gameconfig } from "pixelpai_proto";
import { DragDropIcon } from "./dragDropIcon";
import { IToolTip } from "./tips/itoolTip";
import { Render } from "../../render";
export declare class ItemSlot implements IListItemComponent {
    toolTipCon: Phaser.GameObjects.Container;
    index: number;
    protected toolTip: IToolTip;
    protected mData: op_gameconfig.Item;
    protected mRender: Render;
    protected mScene: Phaser.Scene;
    protected mResStr: string;
    protected mResPng: string;
    protected mResJson: string;
    protected mResSlot: string;
    protected mIcon: DragDropIcon;
    protected mAnimationCon: Phaser.GameObjects.Sprite;
    protected mSubScriptSprite: Phaser.GameObjects.Sprite;
    protected mSubScriptRes: string;
    protected itemBG: Phaser.GameObjects.Sprite;
    protected mSelectSprite: Phaser.GameObjects.Sprite;
    protected mSelectRes: string;
    protected minitialize: boolean;
    protected mWid: number;
    protected mHei: number;
    protected isTipBoo: boolean;
    constructor(scene: Phaser.Scene, render: Render, parentCon: Phaser.GameObjects.Container, x: number, y: number, resStr: string, respng: string, resjson: string, resSlot: string, selectRes?: string, subscriptRes?: string);
    set hasTip(value: boolean);
    get hasTip(): boolean;
    createUI(): void;
    getView(): any;
    getBg(): Phaser.GameObjects.Sprite;
    getIcon(): DragDropIcon;
    dataChange(val: any): void;
    destroy(): void;
    protected setToolTipData(text: string): void;
    protected onLoadCompleteHandler(): void;
    protected downHandler(pointer: any): void;
    protected overHandler(pointer: any): void;
    protected outHandler(pointer: any): void;
}
