import { Render } from "gamecoreRender";
import { op_client } from "pixelpai_proto";
export declare class PicaFurnitureComposePanel extends Phaser.GameObjects.Container {
    protected render: Render;
    private mBackground;
    private topBackground;
    private mCategoriesBar;
    private mCategoryCon;
    private mPreCategoryBtn;
    private mSelectedCategeories;
    private mPropGrid;
    private mPropGridBg;
    private mCategoryScroll;
    private composeBtn;
    private furiAnimation;
    private starCount;
    private mSelectedItemData;
    private subCategoryType;
    private dpr;
    private zoom;
    private key;
    constructor(scene: Phaser.Scene, render: Render, width: number, height: number, dpr: number, zoom: number);
    resize(w: number, h: number): void;
    setCategories(): void;
    setGridProp(props: any[]): void;
    updateGridProp(props: any[]): void;
    setProps(props: any[]): void;
    setStarData(value: number): void;
    updateSelectItemDatas(props: any[]): void;
    setComposeResult(reward: op_client.ICountablePackageItem): void;
    destroy(): void;
    queryRefreshPackage(update: any): void;
    protected init(): void;
    private createNineButton;
    private onSelectSubCategoryHandler;
    private queryPackege;
    private onSelectItemHandler;
    private onComposeBtnHandler;
    private checkSelectItemDatas;
    private onFuriComposeAnimationHandler;
}
