import { Render } from "gamecoreRender";
import { op_client } from "pixelpai_proto";
export declare class PicaRecastePanel extends Phaser.GameObjects.Container {
    protected render: Render;
    private mBackground;
    private mCategoriesBar;
    private mCategoryCon;
    private mTopBg;
    private mPreCategoryBtn;
    private mSelectedCategeories;
    private mPropGrid;
    private mPropGridBg;
    private mCategoryScroll;
    private confirmBtn;
    private displayPanel;
    private starCount;
    private categoryType;
    private mSelectedItemData;
    private mSelectedItem;
    private mRecasteItemData;
    private labelTipTex;
    private mDetailBubble;
    private dpr;
    private zoom;
    private recastData;
    private key;
    private isBag;
    constructor(scene: Phaser.Scene, render: Render, width: number, height: number, dpr: number, zoom: number);
    resize(w: number, h: number): void;
    setRecasteResult(data: op_client.CountablePackageItem): void;
    setCategories(subcategorys: any[]): void;
    setProp(props: any[]): void;
    setStarData(value: number): void;
    setRecasteItemData(data: op_client.ICountablePackageItem, blueprint: boolean): void;
    destroy(): void;
    queryRecasteList(): void;
    protected init(): void;
    private createNineButton;
    private onSelectSubCategoryHandler;
    private queryPackege;
    private onSelectItemHandler;
    private clearRecastData;
    private onConfirmBtnHandler;
    private onDisplayPanelHandler;
}
