import { op_client } from "pixelpai_proto";
import { UiManager } from "gamecoreRender";
import { PicaBasePanel } from "../pica.base.panel";
import { ISocial } from "../../../structure";
export declare class PicaNewRolePanel extends PicaBasePanel {
    private blackGraphic;
    private bg;
    private nameImage;
    private openBigBtn;
    private headAvatar;
    private content;
    private levelLabel;
    private followBtn;
    private tradingBtn;
    private actionContanier;
    private roleData;
    private followed;
    constructor(uiManager: UiManager);
    resize(width?: number, height?: number): void;
    onShow(): void;
    addListen(): void;
    removeListen(): void;
    init(): void;
    setRoleData(content: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_PKT_ANOTHER_PLAYER_INFO): void;
    setActionDatas(datas: ISocial[]): void;
    setFollowButton(follow: boolean): void;
    private playMove;
    private onOpeningCharacterHandler;
    private onFollowHandler;
    private onTradingHandler;
    private onPeopleActionHandler;
    private OnCloseHandler;
}
