
export enum LoadState {
    ENTERWORLD,
    DOWNLOADGAMECONFIG,
    DOWNLOADSCENECONFIG,
    PARSECONFIG,
    WAITENTERROOM,
    LOADINGRESOURCES,
    LOGINGAME,
    CREATESCENE,
}

export enum PlaySceneLoadState {
    CREATING_SCENE,
    CREATING_ROOM,
    LOAD_COMPOLETE,
}
