import { op_client, op_pkt_def } from "pixelpai_proto";
import { BasePanel, UiManager } from "gamecoreRender";
export declare class PicaWorkPanel extends BasePanel {
    private mBackground;
    private bg;
    private titlebg;
    private tilteName;
    private closeBtn;
    private mGameScroll;
    private content;
    private itemtips;
    private timesPorgress;
    private powerProgress;
    private helpBtn;
    private workItems;
    private selectItem;
    constructor(uiManager: UiManager);
    resize(width?: number, height?: number): void;
    show(param?: any): void;
    addListen(): void;
    removeListen(): void;
    preload(): void;
    init(): void;
    setWorkDataList(content: op_client.OP_VIRTUAL_WORLD_RES_CLIENT_PKT_JOB_LIST): void;
    setProgressData(enery: op_pkt_def.IPKT_Property, work: op_pkt_def.IPKT_Property): void;
    destroy(): void;
    private onHelpHandler;
    private OnClosePanel;
    private onPointerUpHandler;
    private onSendHandler;
    private onItemInfoTips;
    private getDesText;
}
