import { IFramesModel, ISprite } from "structure";
import { op_client } from "pixelpai_proto";
import { IRoomService } from "..";
import { BlockObject } from "../block/block.object";
import { IPos } from "structure";
export declare class Wall extends BlockObject {
    protected mModel: ISprite;
    protected mDisplayInfo: IFramesModel;
    protected mId: number;
    constructor(sprite: ISprite, roomService: IRoomService);
    startMove(): void;
    stopMove(): void;
    setModel(val: ISprite): Promise<void>;
    updateModel(val: op_client.ISprite): void;
    load(displayInfo: IFramesModel): void;
    play(animationName: string): void;
    setDirection(val: number): void;
    getDirection(): number;
    setPosition(p: IPos): void;
    showNickname(): void;
    hideNickname(): void;
    showRefernceArea(): void;
    hideRefernceArea(): void;
    showEffected(): void;
    turn(): void;
    setAlpha(val: number): void;
    scaleTween(): void;
    setQueue(): void;
    completeAnimationQueue(): void;
    update(): void;
    mount(): this;
    unmount(): Promise<this>;
    addMount(): this;
    removeMount(): Promise<void>;
    getInteractivePositionList(): Promise<any[]>;
    destroy(): void;
    protected createDisplay(): Promise<any>;
    protected addDisplay(): Promise<any>;
    protected removeDisplay(): Promise<any>;
    protected setDepth(): void;
    get id(): number;
    get dir(): number;
    get model(): ISprite;
    set model(val: ISprite);
    get currentAnimationName(): string;
    get created(): boolean;
}
