import { NineSliceButton } from "apowophaserui";
import { BasePanel, UiManager } from "gamecoreRender";
import { ICountablePackageItem } from "picaStructure";
export declare class PicaFurniFunPanel extends BasePanel {
    static PICAFURNIFUN_SHOW: string;
    confirmBtn: NineSliceButton;
    private blackGraphic;
    private bg;
    private bgicon;
    private titleimage;
    private titleName;
    private mDetailDisplay;
    private materialCon;
    private materialGameScroll;
    private content;
    private closeBtn;
    private selectMaterial;
    private itemName;
    private itemtips;
    private materials;
    constructor(uiManager: UiManager);
    resize(w: number, h: number): void;
    show(param?: any): void;
    addListen(): void;
    removeListen(): void;
    preload(): void;
    init(): void;
    destroy(): void;
    setFuritDisplay(): void;
    isTeamBuild(): boolean;
    _getDisplayData(): any;
    _getMaterialData(): any;
    setMaterialsData(materials: ICountablePackageItem[]): void;
    private createProtocolObject;
    private setMaterialItems;
    private onConfirmBtnClick;
    private OnClosePanel;
    private onMaterialItemHandler;
    private onItemTipsHideHandler;
    private setTipsPosition;
}
