import { BasePanel, UiManager } from "gamecoreRender";
export declare class PicaPropFunPanel extends BasePanel {
    private uiManager;
    itemCount: number;
    private itemName;
    private titleName;
    private mDetailDisplay;
    private pricText;
    private priceBg;
    private mCoinIcon;
    private itemCountText;
    private itemData;
    private confirmHandler;
    private confirmHandlerAddData;
    private cancelHandler;
    private blackGraphic;
    private content;
    private cancelBtn;
    private confirmBtn;
    private slider;
    private thumb;
    private line;
    private prop;
    constructor(uiManager: UiManager);
    resize(w: number, h: number): void;
    show(param?: any): void;
    addListen(): void;
    removeListen(): void;
    preload(): void;
    init(): void;
    destroy(): void;
    setProp(config: any): void;
    setResource(content: any): void;
    private updateData;
    private onCancelBtnHandler;
    private onConfirmBtnHandler;
    private onSliderValueHandler;
    private calcuSliderValue;
    private lineSliderValue;
}
